### ISSUE TITLE
Tiling?

### ISSUE THREAD

**Issue by noppelmax** [cbdevnet/xecho#13]
Hey,

wie wurde denn das Tiling in der Info Fachschaft gemacht? Läuft da nochmal ein Tiling Manager? Wenn ja, welcher? Danke für deine Mühe.

Max

**Comment by subpathdev** [comment]
Hallo,

in der Fachschaft läuft ein ratpoison (vergleiche dazu: https://en.wikipedia.org/wiki/Ratpoison). Dieser wird mit dem Programm statusdisplay gestarted, welches auch die Verwaltung der Fenster / Programme übernimmt. Das entsprechede Repo findest du hier: https://github.com/fsmi/statusdisplay

Gruß
Jan

**Comment by cbdevnet** [comment]
Jop, was @subpathdev sagt, fuer ratpoison haben wir uns dann noch einen Manager/Init-system geschrieben, das ist https://github.com/fsmi/rpcd

**Comment by noppelmax** [comment]
Hey, ich danke euch! Das hilft mir weiter! ;)
