### ISSUE TITLE
Makefile broken with freetype2

### ISSUE THREAD

**Issue by paulie-g** [cbdevnet/xecho#14]
With freetype2, freetype-config is deprecated and pkg-config has to be used.

```
CFLAGS?=-g -Wall $(shell pkg-config --cflags freetype2)
LDLIBS?=$(shell plg-config --libs freetype2) -lXft -lm -lXext -lX11
```

The above works for me on my Arch-current system.

**Comment by cbdevnet** [comment]
Hi, thanks for the report - should be fixed with the PR :)
